In [2]:
import numpy as np
import pandas as pd


In [9]:
#import dataset
dataset=pd.read_csv("data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  27.0  67000.0       Yes

In [13]:
x=dataset[['Country','Age','Salary']].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 27.0, 67000.0]], dtype=object)

In [14]:
y=dataset[['Purchased']].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [15]:
#Handling Missing data 

from sklearn.impute import SimpleImputer

In [26]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
impute=imputer.fit(x[:,1:3])   #fit(x[row,column])
x[:,1:3]=impute.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 37.666666666666664, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 27.0, 67000.0]], dtype=object)

In [30]:
# categorical data #encoding 

from sklearn.preprocessing import LabelEncoder

In [33]:
lable_encoder_x=LabelEncoder()
x[:,0]=lable_encoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 37.666666666666664, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 27.0, 67000.0]], dtype=object)

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
onehotencode=OneHotEncoder()
onehotencode.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [39]:
lable_encoder_y=LabelEncoder()
y=lable_encoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [42]:
#divide into training  &test data 
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_train

array([[0, 27.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, 37.666666666666664, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [48]:
x_test

array([[1, 30.0, 54000.0],
       [1, 50.0, 83000.0],
       [1, 40.0, 63777.77777777778]], dtype=object)

In [51]:
#Scalling 

from sklearn.preprocessing import StandardScaler

In [52]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_train

array([[-0.8660254 , -1.32130548,  0.44897083],
       [ 1.15470054, -1.32130548, -1.41706417],
       [ 1.15470054,  0.13668677, -1.0242147 ],
       [-0.8660254 ,  1.54911677,  1.62751925],
       [ 1.15470054,  0.18224903, -0.14030338],
       [-0.8660254 ,  1.00236967,  0.94003267],
       [-0.8660254 , -0.22781129, -0.43494049]])

In [53]:
x_test=sc_x.fit_transform(x_test)
x_test

array([[ 0.        , -1.22474487, -1.07298811],
       [ 0.        ,  1.22474487,  1.33431759],
       [ 0.        ,  0.        , -0.26132948]])

In [60]:
pip install notebook --version

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.
